### ISSUE TITLE
Error Reading fast5

### ISSUE THREAD

**Issue by mattdmem** [giesselmann/STRique#3]
Hello,

I get error reading fast5 when trying to run your tool. Any ideas? We are using MinIT and the latest version of MinKnow (19). I think these are multi read fast5s? is this a problem?

Thanks

Matt

**Comment by LynnLy** [comment]
Multi fast5s were released relatively recently, so I don't think they are compatible with this tool. You can use `multi_to_single_fast5` from [ONT fast5 api](https://github.com/nanoporetech/ont_fast5_api) to convert your files to the old single fast5 format and then use STRique.

**Comment by giesselmann** [comment]
@LynnLy is right, so far we support only the single read fast5 format.
I think I can patch it in, possibly next week.
Pay

**Comment by mattdmem** [comment]
Patching it in would be great! Thanks!

**Comment by mattdmem** [comment]
@LynnLy's method worked - although there were so many fast5s it was taking FOREVER, so I grabbed the relevant read ids from the alignment and just put them in a separate folder.

**Comment by giesselmann** [comment]
@mattdmem 
With version v0.2.0 we now support bulk-fast5.
I had to change the format of the fast5Index, any *index.json* generated with previous STRique versions won't work. The reworked command line now requires an index file instead of the raw directory. The index is compatible with the one generated from our [nanopype](https://github.com/giesselmann/nanopype) pipeline.
Since I also changed the location of the submodules, I would recommend starting with a clean installation as documented in the README. Apologize for that.
Please also note that we now provide a Docker container to address the installation / dependency issues around pomegranate and networkx.
